import { CrmShell } from "@/components/CrmShell";
import { favoriteTrackingPresentation } from "@/lib/election-favorite";
import { trpc } from "@/lib/trpc";
import { CalendarClock, ChevronLeft, ChevronRight, ExternalLink, Search, Star, UsersRound } from "lucide-react";
import React, { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const STATUS_OPTIONS = ["Novo", "Abordado", "Respondeu", "Não respondeu", "Interessado", "Follow-up", "Proposta enviada", "Fechado", "Perdido"] as const;
type Favorite = { id: number; status: typeof STATUS_OPTIONS[number]; lastContactAt: Date | null; followUpAt: Date | null; note: string | null };
type FavoriteCandidate = { id: number; candidateName: string; ballotName: string | null; state: string; cargo: string; party: string | null; candidateStatus: string | null; favorite: Favorite };

function formatDate(value: Date | null) {
  return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(value)) : "Não registrado";
}

export default function ElectionFavorites() {
  const utils = trpc.useUtils();
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<string>("");
  const [page, setPage] = useState(1);
  useEffect(() => setPage(1), [query, status]);
  const input = useMemo(() => ({ page, pageSize: 18, ...(query.trim() ? { query: query.trim() } : {}), ...(status ? { status: status as Favorite["status"] } : {}) }), [page, query, status]);
  const { data, isLoading } = trpc.crm.electionResearch.listFavorites.useQuery(input);
  const removeFavorite = trpc.crm.electionResearch.setFavorite.useMutation({
    onSuccess: () => { utils.crm.electionResearch.listFavorites.invalidate(); utils.crm.electionResearch.listCandidates.invalidate(); toast.success("Candidatura removida dos favoritos."); },
    onError: error => toast.error(error.message),
  });
  const pages = Math.max(1, Math.ceil((data?.total ?? 0) / 18));

  return <CrmShell title="Candidaturas favoritas" subtitle="Acompanhamento comercial das candidaturas que você marcou"><div className="space-y-5">
    <section className="overflow-hidden rounded-2xl border border-amber-300/15 bg-[radial-gradient(circle_at_85%_0%,rgba(251,191,36,0.11),transparent_30%),rgba(255,255,255,0.035)] p-5 shadow-[0_16px_50px_rgba(0,0,0,0.11)]"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-amber-200/80"><Star className="h-3.5 w-3.5 fill-current" /> Acompanhamento pessoal</div><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-white">Favoritos eleitorais</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Centralize as candidaturas com as quais você está conversando e retome rapidamente o perfil, o histórico e os próximos passos comerciais.</p></div><a href="/base-eleitoral" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[0.05] px-4 text-xs font-medium text-slate-200 transition hover:border-cyan-300/30 hover:text-cyan-100"><UsersRound className="h-3.5 w-3.5" /> Explorar base eleitoral</a></div></section>
    <section className="flex flex-col gap-3 rounded-2xl border border-white/8 bg-white/[0.035] p-4 sm:flex-row"><label className="flex h-11 flex-1 items-center gap-2 rounded-xl border border-white/8 bg-[#031126]/70 px-3 focus-within:border-cyan-300/35"><Search className="h-4 w-4 text-slate-500" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar nome, cargo ou partido" className="h-full min-w-0 flex-1 bg-transparent text-sm text-slate-100 outline-none placeholder:text-slate-600" /></label><label className="flex h-11 min-w-[190px] items-center gap-2 rounded-xl border border-white/8 bg-white/[0.025] px-3"><span className="text-[10px] text-slate-500">Estágio</span><select value={status} onChange={event => setStatus(event.target.value)} className="min-w-0 flex-1 bg-transparent text-xs text-slate-200 outline-none"><option value="">Todos</option>{STATUS_OPTIONS.map(option => <option className="bg-[#0b1c35]" key={option}>{option}</option>)}</select></label></section>
    {isLoading ? <div className="grid min-h-72 place-items-center rounded-2xl border border-white/8 bg-white/[0.035] text-sm text-slate-500">Carregando favoritos...</div> : !data?.items.length ? <EmptyFavorites filtered={Boolean(query || status)} /> : <><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.items.map(candidate => <FavoriteCard key={candidate.id} candidate={candidate} removing={removeFavorite.isPending} onRemove={() => removeFavorite.mutate({ candidateId: candidate.id, favorite: false })} />)}</section><footer className="flex items-center justify-between rounded-2xl border border-white/8 bg-white/[0.035] px-4 py-3"><span className="text-xs text-slate-500">{data.total.toLocaleString("pt-BR")} favorita(s)</span><div className="flex items-center gap-2"><button disabled={page === 1} onClick={() => setPage(current => current - 1)} className="grid h-8 w-8 place-items-center rounded-lg border border-white/8 text-slate-400 disabled:opacity-35"><ChevronLeft className="h-4 w-4" /></button><span className="text-xs text-slate-400">{page} / {pages}</span><button disabled={page >= pages} onClick={() => setPage(current => current + 1)} className="grid h-8 w-8 place-items-center rounded-lg border border-white/8 text-slate-400 disabled:opacity-35"><ChevronRight className="h-4 w-4" /></button></div></footer></>}
  </div></CrmShell>;
}

function FavoriteCard({ candidate, removing, onRemove }: { candidate: FavoriteCandidate; removing: boolean; onRemove: () => void }) {
  const presentation = favoriteTrackingPresentation(candidate.favorite);
  return <article className="group rounded-2xl border border-white/8 bg-white/[0.035] p-4 shadow-[0_12px_35px_rgba(0,0,0,0.08)] transition hover:border-amber-300/25 hover:bg-white/[0.05]"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-300/[0.1] text-xs font-semibold text-amber-100">{candidate.state}</span><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><a href={`/candidaturas/${candidate.id}`} className="block truncate text-sm font-semibold text-slate-100 transition hover:text-cyan-100">{candidate.candidateName}</a><p className="mt-1 truncate text-xs text-slate-500">{candidate.ballotName || "Nome de urna não publicado"}</p></div><button onClick={onRemove} disabled={removing} title="Remover dos favoritos" aria-label="Remover dos favoritos" className="grid h-8 w-8 shrink-0 place-items-center rounded-lg border border-amber-300/35 bg-amber-300/[0.12] text-amber-100 transition hover:bg-rose-300/[0.12] hover:text-rose-100 disabled:opacity-50"><Star className="h-3.5 w-3.5 fill-current" /></button></div><p className="mt-3 text-xs text-slate-300">{candidate.cargo} · {candidate.party || "Sem partido divulgado"}</p><div className="mt-3 flex flex-wrap gap-2"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] ring-1 ${presentation?.tone ?? "text-slate-400 ring-white/10"}`}>{presentation?.label ?? candidate.favorite.status}</span>{candidate.candidateStatus && <span className="rounded-full bg-white/[0.05] px-2 py-1 text-[10px] text-slate-400">{candidate.candidateStatus}</span>}</div><dl className="mt-4 grid grid-cols-2 gap-2 border-t border-white/[0.06] pt-3"><div><dt className="text-[10px] uppercase tracking-[0.1em] text-slate-600">Último contato</dt><dd className="mt-1 text-xs text-slate-300">{formatDate(candidate.favorite.lastContactAt)}</dd></div><div><dt className="text-[10px] uppercase tracking-[0.1em] text-slate-600">Próximo follow-up</dt><dd className="mt-1 flex items-center gap-1 text-xs text-amber-100"><CalendarClock className="h-3 w-3" />{formatDate(candidate.favorite.followUpAt)}</dd></div></dl>{candidate.favorite.note && <p className="mt-3 line-clamp-2 rounded-xl bg-[#031126]/55 px-3 py-2 text-xs leading-5 text-slate-400">{candidate.favorite.note}</p>}<a href={`/candidaturas/${candidate.id}`} className="mt-4 inline-flex items-center gap-1.5 text-xs font-medium text-cyan-200 transition hover:text-cyan-100">Abrir perfil e histórico <ExternalLink className="h-3 w-3" /></a></div></div></article>;
}

export function EmptyFavorites({ filtered }: { filtered: boolean }) { return <section className="grid min-h-80 place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[0.025] p-8 text-center"><div><Star className="mx-auto h-7 w-7 text-amber-200/60" /><h2 className="mt-4 font-display text-xl font-semibold text-slate-100">{filtered ? "Nenhuma favorita corresponde aos filtros" : "Sua lista de favoritos está vazia"}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{filtered ? "Altere a busca ou o estágio comercial para localizar uma candidatura já favoritada." : "Na Base Eleitoral, use a estrela para guardar as candidaturas com as quais você está conversando."}</p>{!filtered && <a href="/base-eleitoral" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-[#06203c] transition hover:bg-cyan-200"><UsersRound className="h-3.5 w-3.5" /> Ir para Base Eleitoral</a>}</div></section>; }
