import { CrmShell } from "@/components/CrmShell";
import { getCandidatePublicContacts } from "@/lib/election-contact";
import { favoriteTrackingPresentation } from "@/lib/election-favorite";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronLeft, ChevronRight, ExternalLink, Filter, Instagram, MessageCircle, Search, ShieldAlert, Star, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const STATES = ["AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"];
const instagramOptions = ["", "Verificado", "Provável — requer revisão", "Não localizado"] as const;

type CandidateFavorite = { id: number; status: string; lastContactAt: Date | null; followUpAt: Date | null } | null;
type CandidateRow = { id: number; candidateName: string; ballotName: string | null; officialCandidateId: string; state: string; cargo: string; party: string | null; candidateStatus: string | null; ballotAvailability: "Sim" | "Não" | "Em análise"; instagramVerification: string; primaryInstagram: string | null; declaredProfiles: string[] | null; favorite: CandidateFavorite };

export default function ElectionCandidates() {
  const utils = trpc.useUtils();
  const { data: collections = [] } = trpc.crm.electionResearch.listCollections.useQuery();
  const selected = collections.find(collection => collection.processStatus === "concluida") ?? collections[0];
  const { data: summary } = trpc.crm.electionResearch.getCollection.useQuery({ id: selected?.id ?? 1 }, { enabled: Boolean(selected) });
  const [query, setQuery] = useState("");
  const [state, setState] = useState("");
  const [cargo, setCargo] = useState("");
  const [instagram, setInstagram] = useState<(typeof instagramOptions)[number]>("");
  const [page, setPage] = useState(1);
  useEffect(() => setPage(1), [query, state, cargo, instagram, selected?.id]);
  const input = useMemo(() => ({ collectionId: selected?.id ?? 1, page, pageSize: 25, ...(query ? { query } : {}), ...(state ? { state } : {}), ...(cargo ? { cargo } : {}), ...(instagram ? { instagramVerification: instagram } : {}) }), [selected?.id, page, query, state, cargo, instagram]);
  const { data, isLoading } = trpc.crm.electionResearch.listCandidates.useQuery(input, { enabled: Boolean(selected) });
  const prepareContact = trpc.crm.electionResearch.prepareContact.useMutation({ onSuccess: result => { window.open(result.url, "_blank", "noopener,noreferrer"); toast.success(result.channel === "whatsapp" ? "WhatsApp aberto com mensagem preenchida." : "Instagram aberto e interação registrada."); }, onError: error => toast.error(error.message) });
  const setFavorite = trpc.crm.electionResearch.setFavorite.useMutation({ onSuccess: ({ favorite }) => { utils.crm.electionResearch.listCandidates.invalidate(); toast.success(favorite ? "Candidatura adicionada aos favoritos." : "Candidatura removida dos favoritos."); }, onError: error => toast.error(error.message) });
  const pages = Math.max(1, Math.ceil((data?.total ?? 0) / 25));

  return <CrmShell title="Base de candidaturas" subtitle="Consulta auditável das candidaturas estaduais de 2026"><div className="space-y-5">
    <section className="rounded-2xl border border-white/8 bg-white/[0.035] p-4 shadow-[0_16px_50px_rgba(0,0,0,0.11)]"><div className="flex flex-col gap-3 xl:flex-row"><div className="flex h-11 flex-1 items-center gap-2 rounded-xl border border-white/8 bg-[#031126]/70 px-3 focus-within:border-cyan-300/35"><Search className="h-4 w-4 text-slate-500" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar por nome, nome de urna ou Instagram" className="h-full min-w-0 flex-1 bg-transparent text-sm text-slate-100 outline-none placeholder:text-slate-600" /></div><div className="flex flex-wrap gap-2"><Selector value={state} onChange={setState} label="UF" options={STATES} /><Selector value={cargo} onChange={setCargo} label="Cargo" options={(summary?.byCargo ?? []).map(item => item.cargo)} /><Selector value={instagram} onChange={value => setInstagram(value as typeof instagram)} label="Instagram" options={[...instagramOptions].filter(Boolean)} /></div></div><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Filter className="h-3.5 w-3.5" /> Favorite as candidaturas com as quais está conversando para editar o acompanhamento comercial no perfil.</p></section>
    <section className="overflow-hidden rounded-2xl border border-white/8 bg-white/[0.035] shadow-[0_16px_50px_rgba(0,0,0,0.11)]"><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1230px] text-left"><thead><tr className="border-b border-white/[0.07] text-[10px] uppercase tracking-[0.12em] text-slate-500"><th className="px-5 py-4">Candidatura</th><th className="px-3 py-4">UF</th><th className="px-3 py-4">Cargo</th><th className="px-3 py-4">Partido</th><th className="px-3 py-4">Situação</th><th className="px-3 py-4">Urna</th><th className="px-3 py-4">Instagram</th><th className="px-3 py-4">Acompanhamento</th><th className="px-5 py-4">Ações</th></tr></thead><tbody>{isLoading ? <LoadingRows /> : data?.items.map(candidate => <tr key={candidate.id} className="border-b border-white/[0.055] text-sm"><td className="px-5 py-4"><a href={`/candidaturas/${candidate.id}`} className="font-medium text-slate-100 hover:text-cyan-100">{candidate.candidateName}</a><p className="mt-1 text-xs text-slate-500">{candidate.ballotName || "Nome de urna não publicado"} · ID {candidate.officialCandidateId}</p></td><td className="px-3 py-4 text-xs text-slate-300">{candidate.state}</td><td className="px-3 py-4 text-xs text-slate-300">{candidate.cargo}</td><td className="px-3 py-4 text-xs text-slate-300">{candidate.party || "—"}</td><td className="px-3 py-4 text-xs text-slate-300">{candidate.candidateStatus || "—"}</td><td className="px-3 py-4"><span className={`rounded-full px-2 py-1 text-[10px] ${candidate.ballotAvailability === "Sim" ? "bg-emerald-300/10 text-emerald-200" : candidate.ballotAvailability === "Não" ? "bg-rose-300/10 text-rose-200" : "bg-amber-300/10 text-amber-200"}`}>{candidate.ballotAvailability}</span></td><td className="px-3 py-4"><InstagramBadge candidate={candidate} /></td><td className="px-3 py-4"><FavoriteStatus favorite={candidate.favorite} /></td><td className="px-5 py-4"><CandidateActions candidate={candidate} loading={prepareContact.isPending || setFavorite.isPending} onPrepare={channel => prepareContact.mutate({ candidateId: candidate.id, channel })} onFavorite={() => setFavorite.mutate({ candidateId: candidate.id, favorite: !candidate.favorite })} /></td></tr>)}</tbody></table></div>
      <div className="divide-y divide-white/[0.055] lg:hidden">{isLoading ? <div className="p-8 text-center text-sm text-slate-500">Carregando candidaturas...</div> : data?.items.map(candidate => <article key={candidate.id} className="p-4"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-cyan-300/[0.08] text-xs font-semibold text-cyan-200">{candidate.state}</span><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><a href={`/candidaturas/${candidate.id}`} className="block min-w-0 flex-1 truncate text-sm font-medium text-slate-100">{candidate.candidateName}</a><FavoriteButton active={Boolean(candidate.favorite)} loading={setFavorite.isPending} onClick={() => setFavorite.mutate({ candidateId: candidate.id, favorite: !candidate.favorite })} /></div><p className="mt-1 text-xs text-slate-500">{candidate.cargo} · {candidate.party || "Sem partido"}</p><div className="mt-3 flex flex-wrap items-center gap-2"><InstagramBadge candidate={candidate} /><FavoriteStatus favorite={candidate.favorite} /></div><div className="mt-3"><CandidateActions candidate={candidate} loading={prepareContact.isPending} onPrepare={channel => prepareContact.mutate({ candidateId: candidate.id, channel })} onFavorite={() => setFavorite.mutate({ candidateId: candidate.id, favorite: !candidate.favorite })} hideFavorite /></div></div></div></article>)}</div>
      {!isLoading && !data?.items.length && <div className="grid min-h-64 place-items-center p-8 text-center"><div><UsersRound className="mx-auto h-6 w-6 text-slate-600" /><p className="mt-3 text-sm text-slate-300">Nenhuma candidatura encontrada</p><p className="mt-1 text-xs text-slate-500">Ajuste os filtros para consultar a base oficial.</p></div></div>}<footer className="flex items-center justify-between border-t border-white/[0.07] px-4 py-3"><span className="text-xs text-slate-500">{data?.total.toLocaleString("pt-BR") ?? 0} candidatura(s)</span><div className="flex items-center gap-2"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="grid h-8 w-8 place-items-center rounded-lg border border-white/8 text-slate-400 disabled:opacity-35"><ChevronLeft className="h-4 w-4" /></button><span className="text-xs text-slate-400">{page} / {pages}</span><button disabled={page >= pages} onClick={() => setPage(page + 1)} className="grid h-8 w-8 place-items-center rounded-lg border border-white/8 text-slate-400 disabled:opacity-35"><ChevronRight className="h-4 w-4" /></button></div></footer>
    </section></div></CrmShell>;
}

function Selector({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="flex h-11 min-w-[132px] items-center gap-2 rounded-xl border border-white/8 bg-white/[0.025] px-3"><span className="text-[10px] text-slate-500">{label}</span><select value={value} onChange={event => onChange(event.target.value)} className="min-w-0 flex-1 bg-transparent text-xs text-slate-200 outline-none"><option value="">Todos</option>{options.map(option => <option className="bg-[#0b1c35]" key={option}>{option}</option>)}</select></label>; }
function InstagramBadge({ candidate }: { candidate: Pick<CandidateRow, "instagramVerification" | "primaryInstagram"> }) { if (candidate.primaryInstagram) return <a href={candidate.primaryInstagram} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs text-cyan-200 hover:text-cyan-100"><CheckCircle2 className="h-3.5 w-3.5" /> Verificado <ExternalLink className="h-3 w-3" /></a>; return <span className={`inline-flex items-center gap-1.5 text-xs ${candidate.instagramVerification === "Não localizado" ? "text-slate-500" : "text-amber-200"}`}><ShieldAlert className="h-3.5 w-3.5" /> {candidate.instagramVerification}</span>; }
function FavoriteStatus({ favorite }: { favorite: CandidateFavorite }) { const presentation = favoriteTrackingPresentation(favorite); return presentation ? <span className={`inline-flex rounded-full px-2 py-1 text-[10px] ring-1 ${presentation.tone}`}>{presentation.label}</span> : <span className="text-[10px] text-slate-600">Não favoritada</span>; }
function FavoriteButton({ active, loading, onClick }: { active: boolean; loading: boolean; onClick: () => void }) { return <button onClick={onClick} disabled={loading} title={active ? "Remover dos favoritos" : "Favoritar candidatura"} aria-label={active ? "Remover dos favoritos" : "Favoritar candidatura"} className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg border transition disabled:opacity-50 ${active ? "border-amber-300/40 bg-amber-300/15 text-amber-100" : "border-white/10 bg-white/[0.04] text-slate-500 hover:text-amber-100"}`}><Star className={`h-3.5 w-3.5 ${active ? "fill-current" : ""}`} /></button>; }
function CandidateActions({ candidate, loading, onPrepare, onFavorite, hideFavorite = false }: { candidate: CandidateRow; loading: boolean; onPrepare: (channel: "instagram" | "whatsapp") => void; onFavorite: () => void; hideFavorite?: boolean }) { const { instagram, whatsapp } = getCandidatePublicContacts(candidate); return <span className="flex gap-1.5"><a href={`/candidaturas/${candidate.id}`} title="Abrir perfil e histórico" className="grid h-8 w-8 place-items-center rounded-lg border border-cyan-300/20 bg-cyan-300/[0.06] text-cyan-100 hover:bg-cyan-300/[0.12]"><UsersRound className="h-3.5 w-3.5" /></a>{!hideFavorite && <FavoriteButton active={Boolean(candidate.favorite)} loading={loading} onClick={onFavorite} />}{instagram && <button onClick={() => onPrepare("instagram")} disabled={loading} title="Registrar e abrir Instagram público" className="grid h-8 w-8 place-items-center rounded-lg border border-fuchsia-300/20 bg-fuchsia-300/[0.06] text-fuchsia-100 hover:bg-fuchsia-300/[0.12] disabled:opacity-50"><Instagram className="h-3.5 w-3.5" /></button>}{whatsapp && <button onClick={() => onPrepare("whatsapp")} disabled={loading} title="Abrir WhatsApp com mensagem e registrar contato" className="grid h-8 w-8 place-items-center rounded-lg border border-emerald-300/20 bg-emerald-300/[0.06] text-emerald-100 hover:bg-emerald-300/[0.12] disabled:opacity-50"><MessageCircle className="h-3.5 w-3.5" /></button>}</span>; }
function LoadingRows() { return <>{Array.from({ length: 8 }).map((_, index) => <tr key={index}><td colSpan={9} className="px-5 py-5"><div className="h-4 animate-pulse rounded bg-white/[0.06]" /></td></tr>)}</>; }
