import { CrmShell } from "@/components/CrmShell";
import { formatDate } from "@/lib/crm-ui";
import { trpc } from "@/lib/trpc";
import { AlertCircle, CheckCircle2, ChevronRight, FileSpreadsheet, LoaderCircle, Trash2, XCircle } from "lucide-react";
import { useState } from "react";

export default function ImportHistory() {
  const { data = [], isLoading } = trpc.crm.imports.list.useQuery();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const utils = trpc.useUtils();
  const removeImport = trpc.crm.imports.delete.useMutation({ onSuccess: () => { setSelectedId(null); utils.crm.imports.list.invalidate(); utils.crm.dashboard.invalidate(); } });
  const { data: detail, isLoading: loadingDetail } = trpc.crm.imports.get.useQuery({ id: selectedId ?? 1 }, { enabled: Boolean(selectedId) });
  const requestDeletion = () => {
    if (!selectedId || !detail) return;
    const deleteLinkedLeads = window.confirm("Deseja também excluir os leads criados por esta importação? Clique em OK para apagar os leads ou em Cancelar para manter os leads e remover apenas o histórico da importação.");
    const action = deleteLinkedLeads ? "a importação e os leads vinculados" : "somente o histórico da importação";
    if (window.confirm(`Confirma excluir ${action}? Esta ação não poderá ser desfeita.`)) removeImport.mutate({ id: selectedId, deleteLinkedLeads });
  };
  return <CrmShell title="Importações" subtitle="Arquivos de origem e resultados de processamento"><div className="grid gap-5 xl:grid-cols-[1fr_0.8fr]"><section className="overflow-hidden rounded-2xl border border-white/8 bg-white/[0.035] shadow-[0_16px_50px_rgba(0,0,0,0.11)]"><header className="border-b border-white/[0.07] p-5"><h2 className="font-display text-lg font-semibold text-white">Histórico de arquivos</h2><p className="mt-1 text-xs text-slate-500">Cada arquivo permanece ligado aos leads que criou ou atualizou.</p></header>{isLoading ? <Loading /> : <div className="divide-y divide-white/[0.06]">{data.length ? data.map(item => <button onClick={() => setSelectedId(item.id)} key={item.id} className={`flex w-full items-center gap-3 p-4 text-left transition hover:bg-cyan-300/[0.035] ${selectedId === item.id ? "bg-cyan-300/[0.06]" : ""}`}><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[0.05] text-cyan-200"><FileSpreadsheet className="h-4 w-4" /></span><span className="min-w-0 flex-1"><b className="block truncate text-sm font-medium text-slate-200">{item.fileName}</b><small className="mt-1 block text-xs text-slate-500">{formatDate(item.createdAt, true)} · {item.totalRows} linha(s)</small></span><ImportState status={item.status} /><ChevronRight className="h-4 w-4 text-slate-600" /></button>) : <Empty />}</div>}</section><section className="rounded-2xl border border-white/8 bg-white/[0.035] p-5 shadow-[0_16px_50px_rgba(0,0,0,0.11)]">{selectedId ? loadingDetail ? <Loading /> : detail ? <ImportDetail detail={detail} onDelete={requestDeletion} isDeleting={removeImport.isPending} /> : <Empty /> : <div className="grid min-h-64 place-items-center text-center"><div><span className="mx-auto grid h-10 w-10 place-items-center rounded-xl bg-white/[0.045] text-slate-500"><FileSpreadsheet className="h-5 w-5" /></span><p className="mt-3 text-sm text-slate-300">Selecione uma importação</p><p className="mt-1 text-xs text-slate-500">Veja as abas, os campos e os resultados associados.</p></div></div>}</section></div></CrmShell>;
}

function ImportState({ status }: { status: string }) { const map: Record<string, { icon: typeof CheckCircle2; className: string }> = { concluida: { icon: CheckCircle2, className: "text-emerald-300" }, falhou: { icon: XCircle, className: "text-rose-300" }, em_processamento: { icon: LoaderCircle, className: "animate-spin text-cyan-300" }, analisando: { icon: LoaderCircle, className: "animate-spin text-cyan-300" } }; const current = map[status] ?? { icon: AlertCircle, className: "text-amber-300" }; const Icon = current.icon; return <Icon className={`h-4 w-4 ${current.className}`} />; }
function ImportDetail({ detail, onDelete, isDeleting }: { detail: any; onDelete: () => void; isDeleting: boolean }) { const meta = (detail.import.metadata || {}) as { newFields?: string[] }; const stats: Array<[string, number]> = [["Linhas", detail.import.totalRows], ["Criados", detail.import.createdLeads], ["Atualizados", detail.import.updatedLeads], ["Ignorados", detail.import.skippedDuplicates]]; return <div><div className="flex items-start gap-3 border-b border-white/[0.07] pb-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/[0.08] text-cyan-200"><FileSpreadsheet className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h2 className="truncate font-display text-lg font-semibold text-white">{detail.import.fileName}</h2><p className="mt-1 text-xs text-slate-500">Enviado em {formatDate(detail.import.createdAt, true)}</p></div><button onClick={onDelete} disabled={isDeleting} title="Excluir importação" className="grid h-8 w-8 place-items-center rounded-lg border border-rose-300/15 text-rose-300/75 hover:bg-rose-300/10 disabled:opacity-50"><Trash2 className="h-3.5 w-3.5" /></button></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(([label, value]) => <div key={label} className="rounded-xl border border-white/[0.07] bg-[#041126]/40 p-3"><p className="text-[10px] uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold text-slate-100">{value}</p></div>)}</div><div className="mt-6"><h3 className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Abas encontradas</h3><div className="mt-3 space-y-2">{detail.sheets.map((sheet: any) => <div key={sheet.id} className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><div className="flex items-center justify-between"><b className="text-sm text-slate-200">{sheet.name}</b><span className={`text-[10px] ${sheet.isSelected ? "text-cyan-200" : "text-slate-600"}`}>{sheet.isSelected ? "Importada" : "Não importada"}</span></div><p className="mt-1 text-xs text-slate-500">{sheet.totalRows} linhas · {sheet.columnNames.length} campos</p></div>)}</div></div>{meta.newFields?.length ? <div className="mt-6"><h3 className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Novos campos criados</h3><p className="mt-2 text-xs leading-5 text-slate-400">{meta.newFields.join(", ")}</p></div> : null}{detail.import.errorReport?.length ? <div className="mt-6 rounded-xl border border-rose-300/15 bg-rose-300/[0.05] p-3"><p className="text-xs font-medium text-rose-200">Relatório de erros</p>{detail.import.errorReport.map((item: { row: number; reason: string }, index: number) => <p key={index} className="mt-1 text-xs text-rose-100/65">Linha {item.row}: {item.reason}</p>)}</div> : null}</div>; }
function Loading() { return <div className="grid min-h-64 place-items-center"><LoaderCircle className="h-5 w-5 animate-spin text-cyan-300" /></div>; }
function Empty() { return <div className="grid min-h-56 place-items-center text-center"><div><FileSpreadsheet className="mx-auto h-5 w-5 text-slate-600" /><p className="mt-2 text-xs text-slate-500">Nenhuma importação disponível.</p></div></div>; }
